spring:
  application:
    name: visits-service
  config:
    import: optional:configserver:http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com/config-server/

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com/discovery-server/eureka

logging:
  pattern:
    level: trace_id=%mdc{trace_id} span_id=%mdc{span_id} trace_flags=%mdc{trace_flags} %5p

---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com/config-server
