spring:
    application:
        name: discovery-server
    config:
        import: optional:configserver:http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com/config-server/
eureka:
    server:
        enableSelfPreservation: false
# Avoid some debugging logs at startup
logging:
    level:
        org:
            springframework:
                boot: INFO
                web: INFO

---
spring:
    config:
        activate:
            on-profile: docker
        import: configserver:http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com/config-server
