spring:
  application:
    name: admin-server
  config:
    import: optional:configserver:http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com/config-server/

eureka:
  instance:
    preferIpAddress: true
---
spring:
  config:
    activate:
      on-profile: docker
    import: configserver:http://ac9d448751edc4aee94e5b252558f421-1054032099.us-east-1.elb.amazonaws.com/config-server
